### ISSUE TITLE
Decide a consistent URL for Python sources

### ISSUE THREAD

**Issue by livingsilver94** [snekpit/venom#5]
Most Python packages' tarballs are downloaded from pypi.org. This hosting service offers multiple URLs from which to download tarballs:

1. `https://files.pythonhosted.org/packages/AB/CD/EF0123/${name}-${version}.tar.gz`
2. `https://files.pythonhosted.org/packages/source/${name}[0]/${name}/${name}-${version}.tar.gz`
3. `https://pypi.io/packages/source/${name}[0]/${name}/${name}-${version}.tar.gz`

The first one contains a hex identifier. It's ugly to read, but it's easier to get since it's what pypi.org webpages offer. You just copy the URL via your browser.

The others are equivalent, the last one is just shorter.

See examples for `python-dateutil`:

1. `https://files.pythonhosted.org/packages/4c/c4/13b4776ea2d76c115c1d1b84579f3764ee6d57204f6be27119f13a61d0a9/python-dateutil-2.8.2.tar.gz`
2. `https://files.pythonhosted.org/packages/source/p/python-dateutil/python-dateutil-2.8.2.tar.gz`
3. `https://pypi.io/packages/source/p/python-dateutil/python-dateutil-2.8.2.tar.gz`

Assuming we really want a consistent format, which one are we choosing? Personally I'd go with the third since it's easier to the eyes.

**Comment by ReillyBrogan** [comment]
I also hate `#1`. I have no preference between the other two.

**Comment by joebonrichie** [comment]
2 has one less redirect, if that matters at all.

**Comment by pwtail** [comment]
The short-url pythonhosted.org is a redirect to hash-based url.
pypi.io is the worst: it redirects to pypi.org which redirects to short-url pythonhosted.org which redirects to hash-based url.

https://warehouse.pypa.io/api-reference/integration-guide.html#querying-pypi-for-package-urls

**Comment by sunnyflunk** [comment]
> 2 has one less redirect, if that matters at all.

It definitely does, so we will go with 2 as it will be automated in some way which makes 1 unviable. /thread

**Comment by livingsilver94** [comment]
@ikeycode we settled with 2. ?

**Comment by ikeycode** [comment]
2

**Comment by ermo** [comment]
Migrated to serpent-os/recipes
